apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      # imagePullSecrets:
      # - name: testing  # Name of the secret you created
      containers:
      - name: test
        image: 757323807332.dkr.ecr.us-east-1.amazonaws.com/testregistor114:$TAG # Replace with your image details
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
